### ISSUE TITLE
Hey, Can you make this Carousel Infinite?

### ISSUE THREAD

**Issue by Jaypatelbond** [askNilesh/carousel-layout-using-viewPager2#2]
We have many ways to make infinite carousel to ViewPager, still, I'm making an Infinite Carousel with ViewPager 2! And the PageTransformer you used here doesn't work for RTL layout? ViewPager2 supports RTL as well!

**Comment by askNilesh** [comment]
hello @Jaypatelbond  can you share the code that you have used so I can reproduce the issue

**Comment by Jaypatelbond** [comment]
Have a look at the app, its normal demo app. [The App Code](https://github.com/Jaypatelbond/100DaysofCode/tree/master/Android%20Projects/ACRepairPreview)
@askNilesh
